export default {
  // General
  SET_LOADING: 'SET_LOADING',
  INIT: 'INIT',
  SET_INITIALIZED: 'SET_INITIALIZED',
  // Auth
  SET_USER: 'SET_USER',
  REGISTER: 'REGISTER',
  LOGIN_WITH_CREDENTIALS: 'LOGIN_WITH_CREDENTIALS',
  LOGOUT: 'LOGOUT',
  TRY_AUTH: 'TRY_AUTH',
  // Lists
  ADD_LIST: 'ADD_LIST',
  REMOVE_LIST: 'REMOVE_LIST',
  SET_CURRENT_LIST: 'SET_CURRENT_LIST',
  ADD_ITEM_TO_CURRENT_LIST: 'ADD_ITEM_TO_CURRENT_LIST',
  ADD_ITEM_TO_LIST: 'ADD_ITEM_TO_LIST',
  // CHANGE_TODO_NAME: 'CHANGE_TODO_NAME',
  // OVERRIDE_TODO: 'OVERRIDE_TODO',
  // CHANGE_TODO_DESCRIPTION: 'CHANGE_TODO_DESCRIPTION',
  PATCH_ITEM: 'PATCH_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  SYNC_LISTS: 'SYNC_LISTS',
};
